#!/usr/bin/env python3
"""Generate members_updated.csv with scraped email and Facebook data."""
import csv

FIELDNAMES = ["Known via", "Business Name", "Contact Name", "Email Address",
              "Phone Number", "Website URL", "Facebook Page URL", "Business Category", "Notes"]

ROWS = [
    # DINING
    ("", "A Dinner in Paradise", "", "adinnerinparadise@gmail.com", "(305) 905-7732", "https://www.adinnerinparadise.com", "https://www.facebook.com/p/A-Dinner-In-Paradise-100070574721661/", "Dining", ""),
    ("", "A Movable Feast", "", "catering@a-movable-feast.com", "(305) 304-0556", "https://www.a-movable-feast.com", "https://www.facebook.com/AMovableFeastFL/", "Dining", ""),
    ("", "Atlantic's Edge at Cheeca", "", "info@cheeca.com", "(305) 664-4651", "https://www.cheeca.com", "https://www.facebook.com/cheecalodge/", "Dining", ""),
    ("", "Café Moka Islamorada", "", "", "(305) 922-2594", "https://tinyurl.com/4zyppu8r", "https://www.facebook.com/p/Cafe-moka-Islamorada-100054338988390/", "Dining", ""),
    ("", "Captain Craig's Restaurant", "", "", "(305) 852-9424", "https://www.captcraigs.com", "https://www.facebook.com/CaptCraigs/", "Dining", ""),
    ("", "City Hall Café & Wine Bar", "", "", "(305) 852-3354", "https://www.cityhallcafe.net", "https://www.facebook.com/p/City-Hall-Cafe-100063533973853/", "Dining", ""),
    ("", "Coastal Cup & Lounge at Amara Cay Resort", "", "reservations@amaracayresort.com", "(305) 664-0073", "https://www.amaracay.com", "https://www.facebook.com/AmaraCayResort/", "Dining", ""),
    ("", "Crooked Palm Cabana", "", "info@islamoradabeerco.com", "(305) 741-7104", "https://crookedpalmdistillery.com/cabana", "https://www.facebook.com/CrookedPalm/", "Dining", ""),
    ("", "Day Drippin' Coffee", "", "daydrippincoffee@gmail.com", "(704) 780-6724", "https://www.daydrippincoffee.com", "https://www.facebook.com/daydrippincoffee/", "Dining", ""),
    ("", "Drift at the Islander Resort", "", "info@islanderfloridakeys.com", "(305) 664-2031", "https://islanderfloridakeys.com", "https://www.facebook.com/IslanderResort/", "Dining", ""),
    ("", "El Framboyan Cuban Cuisine", "", "", "(305) 922-2949", "https://www.elframboyan.us", "https://www.facebook.com/p/El-Framboyan-Cuban-Cuisine-100082317469917/", "Dining", ""),
    ("", "Enrico's Pizza", "", "", "(305) 852-2200", "https://www.enricospizza.com", "https://www.facebook.com/EnricosIslamorada/", "Dining", ""),
    ("", "F-ing Bagels", "", "fingbagels@gmail.com", "(305) 877-1591", "https://f-ingbagels.com", "https://www.facebook.com/fingbagels/", "Dining", ""),
    ("ILI", "Florida Keys Food Tour", "", "", "(305) 394-1028", "https://www.flkeysfoodtour.com", "https://www.facebook.com/floridakeysfoodtours/", "Dining | Things to Do: Attractions", ""),
    ("", "Green Turtle Inn", "", "briel.jeudy@greenturtleinn.com", "(305) 664-2006", "https://www.greenturtleinn.com", "https://www.facebook.com/GreenTurtleKeys/", "Dining", ""),
    ("", "Hideaway at Three Waters Resort & Marina", "", "", "(305) 664-5300", "https://www.threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Dining", ""),
    ("", "Hog Heaven Sports Bar & Grill", "", "tim@whaleharborgroup.com", "(305) 664-9669", "https://www.hogheavensportsbar.com", "https://www.facebook.com/hogheavenbarandgrill/", "Dining", ""),
    ("", "Hungry Tarpon Restaurant", "", "", "(305) 664-0535", "https://www.hungrytarpon.com", "https://www.facebook.com/hungrytarpon", "Dining", ""),
    ("", "Islamorada Brewery and Distillery", "", "southgm@islamoradabeverages.com", "(305) 440-2162", "https://www.islamoradabreweryanddistillery.com", "https://www.facebook.com/IslamoradaBreweryMM82/", "Dining | Things to Do: Attractions", ""),
    ("", "Islamorada Fish Company", "", "", "(305) 664-9271", "https://www.islamoradafishco.com", "https://www.facebook.com/Ifckeys/", "Dining", ""),
    ("", "Islamorada Shrimp Shack", "", "Islamoradashrimpshack@aol.com", "(305) 664-8433", "https://www.islamoradashrimpshack.com", "https://www.facebook.com/IslamoradaShrimpShack/", "Dining", ""),
    ("", "Island Grill", "", "es@islandgrillkeys.com", "(305) 664-8400", "https://www.keysislandgrill.com", "https://www.facebook.com/islandgrillislamorada/", "Dining", ""),
    ("", "Italian Food Company", "", "ciao@italianfoodcompany.com", "(305) 780-7127", "https://www.italianfoodcompany.com", "", "Dining", ""),
    ("", "Kaiyo Grill & Sushi", "", "KaiyoGrill@KaiyoGrill.com", "(305) 664-5556", "https://www.kaiyokeys.com", "https://www.facebook.com/kaiyokeys/", "Dining", ""),
    ("", "Key Lime Pie Lady", "", "", "(305) 393-9053", "https://www.keylimepielady.com", "https://www.facebook.com/keylimepielady/", "Dining", ""),
    ("", "Keys Chocolates & Ice Cream", "", "info@keylargochocolates.com", "(305) 440-3178", "https://keys-chocolates-ice-cream.business.site", "https://www.facebook.com/KeyLargoChocolates/", "Dining | Shopping: Island Shops And Boutiques", ""),
    ("", "Lazy Days Restaurant", "", "John@lazydaysislamorada.com", "(305) 664-5256", "https://www.lazydaysislamorada.com", "https://www.facebook.com/LazyDaysIslamorada/", "Dining", ""),
    ("", "Lucky Twist at Three Waters Resort & Marina", "", "", "(305) 664-5300", "https://www.threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Dining", ""),
    ("", "Mangrove Mike's Café", "", "connect@mangrovemikescafe.com", "(305) 664-8022", "https://www.mangrovemikescafe.com", "https://www.facebook.com/mangrovemikes/", "Dining", ""),
    ("", "Marker 88 Restaurant", "", "info@marker88.info", "(305) 852-9315", "https://www.marker88.net", "https://www.facebook.com/Marker88/", "Dining", ""),
    ("", "M.E.A.T. Eatery and Taproom", "", "admin@meateatery.com", "(305) 852-3833", "https://www.meateatery.com", "https://www.facebook.com/MEATEateryAndTaproom/", "Dining", ""),
    ("", "Mercado Morada at Three Waters Resort & Marina", "", "", "(305) 664-5300", "https://www.threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Dining", ""),
    ("", "Mia Cucina at Cheeca", "", "info@cheeca.com", "(305) 664-4651", "https://www.cheeca.com", "https://www.facebook.com/cheecalodge/", "Dining", ""),
    ("", "Midway Café & Coffee Bar", "", "info@midwaycafecoffeebar.com", "(305) 664-2622", "https://www.midwaycafecoffeebar.com", "https://www.facebook.com/MidwayCafeCoffee/", "Dining", ""),
    ("", "Morada Bay Café", "", "info@moradabaykeys.com", "(305) 664-0604", "https://www.moradabaykeys.com", "https://www.facebook.com/MoradaBayKeys/", "Dining", ""),
    ("", "Nikai Sushi Bar & Restaurant at Cheeca", "", "info@cheeca.com", "(305) 664-4651", "https://www.cheeca.com", "https://www.facebook.com/cheecalodge/", "Dining", ""),
    ("", "Oceanview Inn & Sports Pub", "", "", "(305) 664-8052", "https://www.theocean-view.com", "https://www.facebook.com/ovsportspub/", "Dining", ""),
    ("", "Off the Hook Churrascaria", "", "offthehookchurrascaria@gmail.com", "(305) 684-2111", "https://www.offthehookchurrascaria.com", "https://www.facebook.com/OffTheHookChurrascaria/", "Dining", ""),
    ("", "Old Tavernier Restaurant", "", "", "(305) 852-6012", "https://www.oldtav.com", "https://www.facebook.com/oldtavmm90/", "Dining", ""),
    ("", "Papa Joe's Waterfront", "", "Info@papajoeswaterfront.com", "(305) 433-4662", "https://papajoeswaterfront.com", "https://www.facebook.com/PapaJoesWaterfront/", "Dining", ""),
    ("", "Pierre's Restaurant", "", "info@moradabaykeys.com", "(305) 664-3225", "https://www.moradabaykeys.com", "https://www.facebook.com/MoradaBayKeys/", "Dining", ""),
    ("", "ReelCatch at Amara Cay Resort", "", "reservations@amaracayresort.com", "(305) 664-0073", "https://www.amaracay.com", "https://www.facebook.com/AmaraCayResort/", "Dining", ""),
    ("", "Sidecar at La Siesta Resort", "", "", "(305) 664-2132", "https://www.islamoradaresortcollection.com", "https://www.facebook.com/LaSiestaResortandMarina/", "Dining", ""),
    ("", "Starbucks at Three Waters Resort & Marina", "", "", "(305) 664-5300", "https://www.threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Dining", ""),
    ("", "Square Grouper Bar and Grill", "", "Squaregrouperislamorada@gmail.com", "(786) 901-5678", "https://www.squaregrouperislamorada.com", "https://www.facebook.com/ISLAMORADASQGR/", "Dining", ""),
    ("", "Sushi Sake", "", "", "(305) 509-7010", "https://sushisakemiami.com/sushi-sake-islamorada", "https://www.facebook.com/61571697715241", "Dining", ""),
    ("", "Tides Beachside Grill at the Islander Resort", "", "info@islanderfloridakeys.com", "(305) 664-2031", "https://www.islanderfloridakeys.com", "https://www.facebook.com/IslanderResort/", "Dining", ""),
    ("", "Tiki Bar at Amara Cay Resort", "", "reservations@amaracayresort.com", "(305) 664-0073", "https://www.amaracay.com", "https://www.facebook.com/AmaraCayResort/", "Dining", ""),
    ("", "Tiki Bar and 25 South at Cheeca", "", "info@cheeca.com", "(305) 664-4651", "https://www.cheeca.com", "https://www.facebook.com/cheecalodge/", "Dining", ""),
    ("", "Tiki Bar at Three Waters Resort & Marina", "", "", "(305) 664-5300", "https://www.threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Dining", ""),
    ("", "Whale Harbor Restaurants and Marina", "", "info@whaleharborrestaurant.com", "(305) 664-4959", "https://www.whaleharborinn.com", "https://www.facebook.com/whale.restaurants/", "Dining", ""),
    ("", "Wahoo's Bar and Grill", "", "arietta@whaleharborgroup.com", "(305) 664-9888", "https://www.wahoosbarandgrill.com", "", "Dining", ""),
    ("", 'Whale Harbor Seafood Buffet and Rooftop Bar "The SandBAR"', "", "", "(305) 664-4940", "https://www.whaleharborsandbar.com", "https://www.facebook.com/pages/Sandbar-Rooftop-at-Whale-Harbor/480936412318444", "Dining", ""),
    ("", "Yahuales Red Tacos", "", "moretes7@hotmail.com", "(818) 220-0091", "https://www.yahualesredtacosfl.com", "https://www.facebook.com/p/Yahuales-red-tacos-100067910251854/", "Dining", ""),
    ("", "Ziggie & Mad Dog's Restaurant", "", "", "(305) 664-3391", "https://www.ziggieandmaddogs.com", "https://www.facebook.com/ZiggieMadDogs/", "Dining", ""),
    # THINGS TO DO: ATTRACTIONS
    ("", "Conch Scramble Charity Golf Tournament", "", "conchscramblecharitygolf@gmail.com", "(305) 393-2725", "https://conchscramble.com", "https://www.facebook.com/conchscramble", "Things to Do: Attractions", ""),
    ("", "Curry Hammock State Park", "", "", "(305) 289-2690", "https://floridastateparks.org", "", "Things to Do: Attractions", ""),
    ("", "Dolphin Research Center", "", "drc@dolphins.org", "(305) 289-1121", "https://dolphins.org", "https://www.facebook.com/DolphinResearchCenter/", "Things to Do: Attractions", ""),
    ("", "Dolphins Plus Bayside", "", "info@dolphinsplus.com", "(305) 451-4060", "https://dolphinsplus.com", "https://www.facebook.com/Dolphinspluspage/", "Things to Do: Attractions", ""),
    ("", "Dolphins Plus Marine Mammal Responder", "", "info@dolphinsplus.com", "(305) 453-4321", "https://connecttoprotect.org", "https://www.facebook.com/connecttoprotectdolphins/", "Things to Do: Attractions", ""),
    ("", "Everglades Alligator Farm", "", "info@everglades.com", "(305) 247-2628", "https://everglades.com", "https://www.facebook.com/EvergladesAlligatorFarm/", "Things to Do: Attractions", ""),
    ("", "Florida Keys Aquarium Encounters", "", "info@floridakeysaquariumencounters.com", "(305) 407-3262", "https://floridakeysaquariumencounters.com", "https://www.facebook.com/Floridakeysaquariumencounters/", "Things to Do: Attractions", ""),
    ("", "Florida Keys Celtic Festival", "", "floridakeyscelticfestival@gmail.com", "(305) 797-1704", "https://floridakeyscelticfestival.com", "https://www.facebook.com/FLKeysCelticFest/", "Things to Do: Attractions", ""),
    ("", "Florida Keys Community Concert Band", "", "", "(305) 451-4530", "https://keyscommunityconcertband.org", "https://www.facebook.com/keyscommunityconcertband/", "Things to Do: Attractions", ""),
    ("", "Florida Keys Concert Association", "", "info@floridakeysconcerts.com", "(305) 324-6982", "https://floridakeysconcerts.com", "https://www.facebook.com/FLKCA/", "Things to Do: Attractions", ""),
    ("", "Florida Keys Eco-Discovery Center", "", "FKEDC@noaa.gov", "(305) 767-3076", "https://floridakeys.noaa.gov", "", "Things to Do: Attractions", ""),
    ("", "Florida Keys Wild Bird Rehabilitation Center", "", "info@fkwbc.org", "(305) 852-4486", "https://keepthemflying.org", "https://www.facebook.com/Keyswildbird/", "Things to Do: Attractions", ""),
    ("", "Founders Park", "", "", "(305) 853-1685", "https://islamorada.fl.us", "", "Things to Do: Attractions", ""),
    ("", "Garden Club of the Upper Keys", "", "gardenclubupperkeys@gmail.com", "(305) 394-4530", "https://gardenclubupperkeys.org", "https://www.facebook.com/GardenClubOfTheUpperKeys/", "Things to Do: Attractions", ""),
    ("", "History of Diving Museum", "", "info@divingmuseum.org", "(305) 664-9737", "https://divingmuseum.org", "https://www.facebook.com/divingmuseum/", "Things to Do: Attractions", ""),
    ("", "Islamorada Community Entertainment", "", "", "(305) 395-6344", "https://keysice.com", "https://www.facebook.com/keyiceFL/", "Things to Do: Attractions", ""),
    ("", "Indian Key Historic State Park", "", "", "(305) 664-2540", "https://floridastateparks.org", "", "Things to Do: Attractions", ""),
    ("", "Island Dolphin Care", "", "contact@islanddolphincare.org", "(305) 451-5884", "https://islanddolphincare.org", "https://www.facebook.com/IDCKeyLargo/", "Things to Do: Attractions", ""),
    ("", "Keys E-Bikes", "", "", "(305) 434-5501", "https://keyselectricbike.com", "https://www.facebook.com/KeysEbikes/", "Things to Do: Attractions", ""),
    ("", "Key Players", "", "jonelle.kop@gmail.com", "(305) 393-1893", "https://thekeyplayers.org", "https://www.facebook.com/TheKeyPlayers/", "Things to Do: Attractions", ""),
    ("", "Key West Day Tours", "", "", "(786) 423-3240", "https://keywestdaytours.com", "", "Things to Do: Attractions", ""),
    ("", "Killshot Spearguns", "", "killshotspearguns@gmail.com", "(239) 850-8862", "https://killshotguns.com", "https://www.facebook.com/killshotspearguns/", "Things to Do: Attractions | Shopping: Island Shops And Boutiques", ""),
    ("", "Lignumvitae Key Botanical State Park", "", "", "(305) 664-2540", "https://floridastateparks.org", "", "Things to Do: Attractions", ""),
    ("", "Long Key State Park", "", "", "(305) 664-4815", "https://floridastateparks.org", "", "Things to Do: Attractions", ""),
    ("", "MarineLab", "", "info@marinelab.org", "(305) 451-1139", "https://marinelab.org", "https://www.facebook.com/MarineLabKeyLargo", "Things to Do: Attractions", ""),
    ("", "Mark Sorensen Youth Sailing Program", "", "john@msysp.org", "(305) 747-2600", "https://msysp.org", "https://www.facebook.com/msysp.uksc/", "Things to Do: Attractions", ""),
    ("", "Matecumbe Historical Trust", "", "info@MatecumbeHistoricalTrust.org", "(305) 393-0940", "https://matecumbehistoricaltrust.org", "https://www.facebook.com/Matecumbehistoricaltrust/", "Things to Do: Attractions", ""),
    ("", "Morada Way Arts and Cultural District", "", "info@moradaway.org", "(305) 664-2471", "https://moradaway.org", "https://www.facebook.com/MoradaWay/", "Things to Do: Attractions | Shopping: Art Galleries", ""),
    ("", "Old Town Trolley Tours of Key West", "", "", "(305) 296-6688", "https://trolleytours.com/key-west", "https://www.facebook.com/OldTownTrolleyKeyWest/", "Things to Do: Attractions", ""),
    ("", "Psychic of the Keys", "", "", "(561) 669-6242", "", "", "Things to Do: Attractions", ""),
    ("", "Pinfish Entertainment", "", "", "(305) 337-0121", "https://pinfishentertainment.com", "https://www.facebook.com/pinfishentertainment/", "Things to Do: Attractions", ""),
    ("", "Protect Center", "", "", "(305) 453-4321", "https://conneccttoprotect.org", "", "Things to Do: Attractions", ""),
    ("", "Rain Barrel Village", "", "contact@rainbarrelvillage.com", "(305) 521-2043", "https://rainbarrelvillage.com", "https://www.facebook.com/RainBarrelVillage/", "Things to Do: Attractions | Shopping: Art Galleries", ""),
    ("", "Robbie's Marina", "", "info@robbies.com", "(305) 664-8070", "https://robbies.com", "https://www.facebook.com/robbiesofislamorada/", "Things to Do: Attractions", ""),
    ("", "South Florida Helicopter Charter and Tours", "", "booking@southfloridahelicoptercharters.com", "(305) 909-0050", "https://southfloridahelicoptercharters.com", "", "Things to Do: Attractions", ""),
    ("", "Theater of the Sea", "", "info@theaterofthesea.com", "(305) 664-2431", "https://theaterofthesea.com", "https://www.facebook.com/theaterofthesea/", "Things to Do: Attractions", ""),
    ("", "Windley Key Fossil Reef Geological State Park", "", "", "(305) 664-2540", "https://floridastateparks.org", "", "Things to Do: Attractions", ""),
    # BEACHES
    ("", "Anne's Public Beach", "", "", "(305) 664-6400", "https://islamorada.fl.us", "", "Things to Do: Beaches", ""),
    ("", "Library Beach Park", "", "", "(305) 393-3377", "", "", "Things to Do: Beaches", ""),
    # CAMPING & RV
    ("", "Bayfront RV", "", "", "(305) 393-3377", "", "", "Things to Do: Camping & Rv Resorts", ""),
    ("", "Fiesta Key RV Resort & Marina", "", "", "(305) 249-1036", "https://rvonthego.com", "https://www.facebook.com/EncoreFiestaKey/", "Things to Do: Camping & Rv Resorts", ""),
    ("", "Grassy Key RV Park & Resort", "", "paradise@grassykeyrvpark.com", "(305) 289-1606", "https://grassykeyrvpark.com", "", "Things to Do: Camping & Rv Resorts", ""),
    ("", "Keys Westys", "", "Reserve@KeysWestys.com", "(786) 326-6763", "https://keyswestys.com", "https://www.facebook.com/KeysWestys/", "Things to Do: Camping & Rv Resorts", ""),
    ("", "Sun Outdoors", "", "", "(786) 841-0030", "https://soislamorada.com", "https://www.facebook.com/SunOutdoorsIslamorada/", "Things to Do: Camping & Rv Resorts", ""),
    # DIVING / WATERSPORTS
    ("", "A Family Fun Boat Tour Company", "", "Info@FamilyFunBoatTours.com", "(305) 896-2915", "https://familyfunboattours.com", "https://www.facebook.com/afamilyfunboattours/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "A Florida Keys Watersports Company", "", "", "(305) 699-9424", "https://floridakeyswatersportscompany.com", "https://www.facebook.com/p/Florida-Keys-WaterSports-co-100063473321456/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "A1A Watersports & Boat Rentals", "", "a1awatersports@gmail.com", "(305) 664-8182", "https://keyswatersports.com", "https://www.facebook.com/A1AWatersports/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Active Disabled Americans", "", "", "(808) 291-8037", "https://activedisabledamericans.org", "https://www.facebook.com/activedisabledamericans/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Allergic to Land Charters", "", "allergictolandcharters@gmail.com", "(305) 393-0842", "https://allergictolandcharters.com", "https://www.facebook.com/allergictolandcharters/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Amoray Dive Resort", "", "amoraydive@amoray.com", "(305) 451-3595", "https://amoray.com", "https://www.facebook.com/amoraydiveresort/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Anchors Away Boat Rentals and Tours", "", "allkeysboatrentals@gmail.com", "(305) 896-2219", "https://anchorsawayboatrentals.com", "https://www.facebook.com/p/Anchors-Away-Boat-Rentals-FL-Keys-100085401613144/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Bay and Reef Company", "", "", "(305) 393-0994", "https://bayandreef.com", "https://www.facebook.com/BayandReef/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Big Pine Kayak Adventures", "", "bigpinekayak@aol.com", "(305) 872-7474", "https://keyskayaktours.com", "https://www.facebook.com/BigPineKayakAdventures/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Blackbeard Private Charters", "", "", "(843) 442-5977", "https://blackbeardcharters.com", "https://www.facebook.com/blackbeardprivatecharters/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Bluewater Adventure the Keys", "", "bluewaterinthekeys@gmail.com", "(305) 619-1020", "https://bluewateradventurethekeys.com", "https://www.facebook.com/bluewateradventurethekeys/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Captain Slate's Scuba Adventures", "", "captainslate@captainslate.com", "(305) 451-3020", "https://captainslate.com", "https://www.facebook.com/1915141055248956", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Caribbean Watersports & Enviro Tours", "", "concierge@caribbeanwatersports.com", "(305) 852-4707", "https://caribbeanwatersports.com", "https://www.facebook.com/p/Caribbean-Watersports-Enviro-Tours-of-the-Florida-Keys-100049067625986/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("ILI", "Clearly Unique Charters", "", "", "(305) 747-8651", "https://clearlyuniquecharters.com", "https://www.facebook.com/ClearlyUniqueCharters/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Conch City Charters", "", "", "(305) 771-4133", "https://conchcitycharters.com", "https://www.facebook.com/conchcitycharters/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Conch Republic Divers", "", "info@conchrepublicdivers.com", "(305) 852-1655", "https://conchrepublicdivers.com", "", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Cruisin' Tikis Islamorada", "", "Cruisintikiswpb@gmail.com", "(844) 244-7500", "https://cruisintikisislamorada.com", "https://www.facebook.com/p/Cruisin-Tikis-Islamorada-61555612694606/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Danger Charters", "", "dangercharters@gmail.com", "(305) 304-7999", "https://dangercharters.com", "https://www.facebook.com/DangerCharters/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Deep Blue Freediving", "", "", "(843) 289-0033", "https://freediveintoblue.com", "https://www.facebook.com/freediveintoblue/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Florida Keys Kayak", "", "floridakeyskayakandski@gmail.com", "(305) 664-4878", "https://kayakthefloridakeys.com", "https://www.facebook.com/floridakeyskayakandski/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Garl's Coastal Kayaking", "", "garlscoastalkayaking@gmail.com", "(305) 393-3223", "https://garlscoastalkayaking.com", "https://www.facebook.com/GarlsCoastalKayaking/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Glassbottom Boat of Islamorada", "", "info@glassbottomtour.com", "(305) 214-5277", "https://glassbottomtour.com", "https://www.facebook.com/GlassBottomBoatsofIslamorada/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("ILI", "I Can See Clear Kayaking", "", "", "(386) 793-1101", "https://clearkayaking.com", "https://www.facebook.com/clearkayaking/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("ILI", "Islamorada Dive Center", "", "", "(305) 664-3483", "https://islamoradadivecenter.com", "https://www.facebook.com/IslamoradaDiveCenter/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("ILI", "Islamorada Luxury Carts", "", "", "(305) 394-5350", "https://islamoradaluxurycarts.com", "https://www.facebook.com/p/Islamorada-Luxury-Carts-100088250103863/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Islamorada Private Charters", "", "", "(305) 395-9691", "https://islamoradaprivatecharters.com", "https://www.facebook.com/islamoradaprivatecharters/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Islamorada Turtle Tours", "", "", "(305) 731-9919", "https://islamoradaturtletours.com", "https://www.facebook.com/p/Islamorada-Turtle-Tours-100089714588390/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Islamorada Watersports Company/Seven Sports", "", "rentals@sevensports.com", "(305) 664-2463", "https://islamoradawatersports.com", "https://www.facebook.com/IslamoradaWatersportsCompany/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Island Adventures", "", "jim@goislandadventures.com", "(305) 394-1436", "https://goislandadventures.com", "https://www.facebook.com/goislandadventures/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Islander Girl Snorkel & Tours", "", "", "(305) 712-0032", "https://islandergirltours.com", "https://www.facebook.com/IslanderGirl.Snorkel/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "JSK Watersports of Florida Keys", "", "jskwatersports@gmail.com", "(305) 998-9373", "https://jskwatersports.com", "https://www.facebook.com/JETSKIRENTALSFLORIDAKEYS/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Key Dives", "", "info@keydives.com", "(305) 664-2211", "https://keydives.com", "https://www.facebook.com/keydives/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Keys Toy Store", "", "", "(305) 563-5030", "https://keystoys.com", "https://www.facebook.com/keystoystores/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "KeyZ Charters", "", "info@keyzcharters.com", "(305) 393-1394", "https://keyzcharters.com", "https://www.facebook.com/KeyZCharters", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Morning Tauk Charters", "", "captainsteady03@gmail.com", "(617) 529-1986", "https://morningtaukcharters.com", "https://www.facebook.com/MorningTAUK/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("ILI", "MYKEYS Tours of Islamorada", "", "", "(305) 360-1731", "https://mykeystours.com", "https://www.facebook.com/p/MyKeys-Tours-of-Islamorada-100076006853802/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Nautical Tiki Cruises Upper Keys", "", "upperkeys@nauticaltiki.com", "(239) 300-5161", "https://nauticaltiki.com", "https://www.facebook.com/NauticalTikiIslamorada/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "PADDLE! the Florida Keys", "", "paddlethefloridakeys@gmail.com", "(305) 434-5930", "https://paddlethefloridakeys.com", "https://www.facebook.com/PaddletheFloridaKeys/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports | Shopping: Island Shops And Boutiques", ""),
    ("", "Parasail the Keys", "", "", "(305) 743-0145", "https://sundancewatersports.org", "https://www.facebook.com/parasailthekeys/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Reef Quest Tours", "", "info@reefquesttours.com", "(305) 405-7738", "https://reefquesttours.com", "", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Sand Bar Time", "", "", "(305) 731-9505", "", "", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Sea Monkeys Watersports", "", "mike@underwaterexploring.com", "(305) 664-4555", "https://seamonkeydivers.com", "https://www.facebook.com/SeaMonkeysWaterSports/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Spray Watersports", "", "", "(305) 664-0075", "https://spraywatersports.com", "https://www.facebook.com/SprayWatersports/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Tides & Tranquility", "", "", "(702) 499-6724", "https://tidesandtranquility.com", "", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    ("", "Wild Dolphin Tours", "", "", "(850) 238-5998", "https://wilddolphintours.com", "https://www.facebook.com/wilddolphintours/", "Things to Do: Diving, Snorkeling, Watersports, Boat Tours, Action Sports", ""),
    # FISHING - BACKCOUNTRY & REEF
    ("", "A Pirate for Hire", "", "captainronbrack@bellsouth.net", "(305) 393-7448", "https://pirateforhirecharters.com", "https://www.facebook.com/pirateforhirecharters/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "All Tackle Backcountry Fishing Charters", "", "", "(305) 942-5224", "https://captaintedwilson.com", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Blue Heaven Charter Company", "", "skye@blueheavencharter.com", "(305) 481-0697", "https://blueheavencharter.com", "https://www.facebook.com/blueheavencharters/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Captain David Borras", "", "Linesout@aol.com", "(305) 393-2423", "", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Captain GW Guide Service", "", "", "(305) 522-3718", "https://captaingw.com", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "CaptainPerry.com", "", "", "(305) 393-0621", "https://captainperry.com", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Casting for Cats", "", "sharellen@netzero.net", "(305) 664-2012", "https://castingforcats.com", "https://www.facebook.com/CastingforCats/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Fish With A Hero", "", "mgibson@fishwithahero.com", "(813) 453-5322", "https://fishwithahero.com", "https://www.facebook.com/fishwithahero/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "FishVerify", "", "support@fishverify.com", "(305) 563-9078", "https://fishverify.com", "https://www.facebook.com/fishverify/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Florida Keys Outfitters", "", "tackle@floridakeysoutfitters.com", "(305) 664-5423", "https://floridakeysoutfitters.com", "https://www.facebook.com/floridakeysoutfitters/", "Things to Do: Fishing - Backcountry & Reef | Shopping: Island Shops And Boutiques", ""),
    ("", "Islamorada Charter Boat Association", "", "islamoradasailfish@gmail.com", "(305) 522-4868", "https://islamoradacharterboatassociation.org", "https://www.facebook.com/p/Islamorada-Charter-Boat-Association-100088397087404/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Lil Fin Charters", "", "", "(305) 852-5989", "", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Salty Morada Fishing Charters", "", "kevinwhite@comcast.net", "(305) 393-9670", "https://saltymoradacharters.com", "https://www.facebook.com/p/Salty-Morada-Charters-100089905145814/", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("", "Triangle Charters", "", "", "(586) 255-3030", "", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    ("ILI", "Wet A Line Charters", "", "", "(561) 260-1184", "https://wetalinecharters.com", "", "Things to Do: Fishing - Backcountry & Reef", ""),
    # FISHING - OFFSHORE
    ("", "EarlyBird Fishing Charters", "", "", "(305) 942-3618", "https://fishearlybird.com", "https://www.facebook.com/FishingChartersEarlyBird/", "Things to Do: Fishing - Offshore", ""),
    ("", "Fearless Sportfishing Charters", "", "capt_hendrix@yahoo.com", "(786) 295-2162", "https://fearlessfishing.net", "https://www.facebook.com/Fearless.Fishing/", "Things to Do: Fishing - Offshore", ""),
    ("", "Gotta Luv Them", "", "", "(954) 900-6080", "https://gottaluvthem.org", "", "Things to Do: Fishing - Offshore", ""),
    ("", "Miller Time Sportfishing", "", "", "(305) 509-2922", "https://millertimesportfishing.com", "https://www.facebook.com/millertimesportfishing/", "Things to Do: Fishing - Offshore", ""),
    ("", "Nick Sheahan Dolphin Rodeo Fishing Tournament", "", "", "(305) 393-3733", "https://nicksheahan.com", "https://www.facebook.com/nicksheahandolphinrodeo/", "Things to Do: Fishing - Offshore", ""),
    ("", "Reef Runner Charters", "", "", "(305) 852-3660", "https://reefrunnerfishing.com", "https://www.facebook.com/102565059138053/", "Things to Do: Fishing - Offshore", ""),
    ("", "Singing Reel Charters", "", "", "(305) 699-8899", "https://singingreelcharters.com", "https://www.facebook.com/singingreelcharters/", "Things to Do: Fishing - Offshore", ""),
    # GROUP TOURS / TRAVEL
    ("", "Amara Cay", "", "reservations@amaracayresort.com", "(305) 664-0073", "https://amaracayresort.com", "https://www.facebook.com/AmaraCayResort/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "Bud N' Mary's Fishing Marina", "", "tackleshop@budnmarys.com", "(305) 664-2461", "https://budnmarys.com", "https://www.facebook.com/budnmarysmarina/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management | Places to Stay: Moderate Lodging", ""),
    ("", "Cheeca Lodge & Spa", "", "info@cheeca.com", "(305) 664-4651", "https://cheeca.com", "https://www.facebook.com/cheecalodge/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management | Places to Stay: Luxury Lodging", ""),
    ("", "Courtyard Marathon by Marriott", "", "", "(305) 289-2100", "https://marriott.com/mthmc", "https://www.facebook.com/CourtyardMarathonFloridaKeys/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management | Places to Stay: Moderate Lodging", ""),
    ("", "Keys Planning and Events", "", "", "(305) 433-9942", "https://keysplanningandevents.com", "https://www.facebook.com/KeysPlanningandEvents/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "Three Waters Resort & Marina", "", "", "(305) 703-1300", "https://threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "Reach Key West, Curio Collection by Hilton", "", "", "(305) 296-5000", "https://reaachresort.com", "https://www.facebook.com/TheReachResort/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management | Places to Stay: Moderate Lodging", ""),
    ("", "Royal Limousine", "", "info@royal-limo.com", "(305) 442-1414", "https://royal-limo.com", "https://www.facebook.com/royallimomiami/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "Safe Harbor Angler House", "", "", "(305) 664-5247", "https://shmarinas.com", "https://www.facebook.com/safeharboranglerhouse/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "Sea La Vie Events and Productions", "", "", "(305) 363-8984", "", "", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "Top Shelf Transportation", "", "", "(714) 955-7086", "https://topshelfcarservice.com", "https://www.facebook.com/TopShelfTransportIslamorada/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management", ""),
    ("", "World Wide Sportsman", "", "", "(305) 664-4615", "https://basspro.com", "https://www.facebook.com/bassproshopsislamorada/", "Things to Do: Group Tours, Travel Agents & Incentive Travel Management | Shopping: Island Shops And Boutiques", ""),
    # MARINAS
    ("", "Abel's Tackle Box General Goods at Three Waters Resort & Marina", "", "", "(305) 664-2900", "https://threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Caloosa Cove Resort and Marina", "", "info@caloosacove.com", "(305) 664-8811", "https://caloosacove.com", "https://www.facebook.com/CaloosaCoveMarina/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle | Places to Stay: Moderate Lodging", ""),
    ("", "Coral Bay Marina", "", "", "(305) 664-3111", "https://coral-bay-marina.com", "https://m.facebook.com/profile.php?id=150510504982288", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "IslaMarina", "", "", "(305) 664-3636", "https://islamarinakeys.com", "https://www.facebook.com/IslaMarinaKeys/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Islamorada Fishing Outfitters", "", "IFOINC22@GMAIL.COM", "(305) 741-7544", "https://islamoradafishingoutfitters.com", "https://www.facebook.com/IslamoradafishingOutfitters", "Things to Do: Marinas, Boat Rentals, Bait & Tackle | Shopping: Island Shops And Boutiques", ""),
    ("", "Island Boat Rentals", "", "", "(305) 664-0091", "https://boatrentalsinthekeys.com", "", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Mangrove Marina & Resort", "", "mangrove@terranova.net", "(305) 852-8380", "https://mangrovemarina.com", "https://www.facebook.com/MangroveMarinaTavernier/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Marina at Three Waters Resort", "", "", "(305) 433-9942", "https://threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Plantation Yacht Harbor Marina", "", "marinainfo@islamorada.fl.us", "(305) 852-2381", "https://pyh.com", "https://www.facebook.com/p/Plantation-Yacht-Harbor-at-Founders-Park-Islamorada-FL-100064590495670/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "SD Marine", "", "snakecreekmarinakeys@gmail.com", "(305) 396-7724", "https://snakecreekmarinakeys.com", "https://www.facebook.com/sdmarinegroup/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Treasure Harbor Marina", "", "info@keysboatrental.com", "(305) 664-9943", "https://treasureharborresort.com", "https://www.facebook.com/TreasureHarborResort/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "Whale Harbor Marina", "", "Dockoffice@whaleharborgroup.com", "(305) 664-4959", "https://whaleharbormarina.com", "https://www.facebook.com/WhaleHarborMarina/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    ("", "World Wide Sportsman Bayside Marina", "", "", "(305) 664-4615", "https://basspro.com", "https://www.facebook.com/bassproshopsislamorada/", "Things to Do: Marinas, Boat Rentals, Bait & Tackle", ""),
    # SALONS / SPAS / FITNESS
    ("", "Aqua Salon & Day Spa", "", "renae@aquasalonislamorada.com", "(305) 902-8286", "https://aquasalonislamorada.com", "https://www.facebook.com/aquasalonislamorada/", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Beyond Traditional Wellness", "", "", "(305) 395-2316", "https://btwfitness.com", "https://www.facebook.com/btw.justgo/", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Blu Bamboo Salon & Spa", "", "", "(305) 664-9342", "https://blubamboo.com", "https://www.facebook.com/p/Blu-Bamboo-Salon-Spa-100054509798345/", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Ciao Bella Salon & Day Spa", "", "info@ciaobellaislamorada.com", "(305) 664-4558", "https://theislamoradaspa.com", "https://www.facebook.com/ciaobellaofislamorada/", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Cirque Salon Studios", "", "", "(305) 800-2477", "https://cirquesalonstudios.com", "https://www.facebook.com/CirqueSalonKeyLargo/", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Key Massage", "", "", "(305) 206-0687", "https://thekeymassage.com", "", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Keys Medical Center / Essence of the Phoenix", "", "", "(305) 664-2490", "", "", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Keys To Nutrition", "", "courtney@thekeystonutrition.com", "(305) 330-1933", "https://thekeystonutrition.com", "https://www.facebook.com/thekeystonutrition/", "Things to Do: Salons, Spas & Fitness", ""),
    ("", "Miller Medicine", "", "wmiller@millermedicine.com", "(305) 453-6097", "https://millermedicine.com", "https://www.facebook.com/millermedspa", "Things to Do: Salons, Spas & Fitness", ""),
    # ART GALLERIES
    ("", "Amy's Creations of the Florida Keys", "", "AmysCreationsFLK@gmail.com", "(321) 557-2581", "", "https://www.facebook.com/p/Amys-Creations-of-the-Florida-Keys-100057423199075/", "Shopping: Art Galleries", ""),
    ("", "DeClue's Custom Framing", "", "", "(305) 664-9385", "", "https://www.facebook.com/declue/", "Shopping: Art Galleries", ""),
    ("", "Finders Keepers Coconuts Art Studio", "", "", "(561) 707-4527", "https://www.paintingthekeys.com", "https://www.facebook.com/finderskeeperscoconuts/", "Shopping: Art Galleries", ""),
    ("", "Florida Keys Council of the Arts", "", "", "(305) 295-4369", "https://www.keysarts.com", "https://www.facebook.com/FloridaKeysCounciloftheArts/", "Shopping: Art Galleries", ""),
    ("", "Gyotaku by Lisa Lee", "", "", "(954) 261-5167", "https://gyotakubylisalee.com", "https://www.facebook.com/GyotakuByLisaLee/", "Shopping: Art Galleries", ""),
    ("", "Hale Gallery, The", "", "hello@thehalegallery.com", "(305) 204-1216", "https://www.thehalegallery.com", "https://www.facebook.com/p/The-Hale-Gallery-100092158036459/", "Shopping: Art Galleries", ""),
    ("", "Islamorada Art Gallery by Pasta", "", "artbypasta@yahoo.com", "(954) 290-4262", "https://www.artbypasta.com", "https://www.facebook.com/artbypasta/", "Shopping: Art Galleries", ""),
    ("", "Jellyfish Daydreams", "", "jellyfishdaydreamstattoo@gmail.com", "(518) 332-1987", "https://www.jellyfishdaydreams.com", "https://www.facebook.com/jellyfishdaydreams", "Shopping: Art Galleries", ""),
    ("", "Key Largo Art Gallery", "", "keylargoartgallery@gmail.com", "(305) 451-0052", "https://Tinyurl.com/3d32tcke", "https://www.facebook.com/p/Key-Largo-Art-Gallery-100063516881934/", "Shopping: Art Galleries", ""),
    ("", "Kona Kai Resort, Gallery and Botanic Gardens", "", "info@konakairesort.com", "(305) 852-7200", "https://www.konakairesort.com", "https://www.facebook.com/KonaKaiResortGalleryandBotanicGarden/", "Shopping: Art Galleries", ""),
    ("", "Livin In Local Color", "", "", "(305) 304-4453", "https://www.livininlocalcolor.com", "https://www.facebook.com/livininlocalcolor/", "Shopping: Art Galleries", ""),
    ("", "Old Road Gallery", "", "", "(305) 852-8935", "https://www.oldroadgallery.com", "https://www.facebook.com/oldroadgallery", "Shopping: Art Galleries", ""),
    ("", "Our Place in Paradise", "", "", "(305) 916-5828", "https://www.ourplaceinparadise.com", "", "Shopping: Art Galleries", ""),
    ("", "Sheri Griffin Photography & Air Plant Jellyfish", "", "", "(305) 731-3321", "https://www.floridakeysgiftshop.etsy.com", "https://www.facebook.com/sherigriffinphotography/", "Shopping: Art Galleries", ""),
    # SHOPPING
    ("", "Blue Marlin Jewelry", "", "", "(305) 664-8004", "https://www.bluemarlinjewelry.com", "https://www.facebook.com/thebluemarlinjewelry/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Cheeca Lodge Signature Store", "", "info@cheeca.com", "(305) 664-4651", "https://www.cheeca.com", "https://www.facebook.com/cheecalodge/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Cigars in the Keys", "", "", "(305) 664-2855", "https://www.cigarsinthekeys.com", "https://www.facebook.com/CigarsInTheKeys/", "Shopping: Island Shops And Boutiques", ""),
    ("", "DePaula Jewelers", "", "depaulajewelers@gmail.com", "(305) 852-4881", "https://www.depaulas.com", "https://www.facebook.com/IslamoradaJewelers", "Shopping: Island Shops And Boutiques", ""),
    ("", "Dixie Aluminum", "", "dixiealum@bellsouth.net", "(305) 852-5104", "https://floridakeyshardware.com", "https://www.facebook.com/p/Dixie-Aluminum-True-Value-100057284806421/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Forest Tek Lumber", "", "ftlsales@keyslumber.com", "(305) 852-4300", "https://www.keyslumber.com", "https://www.facebook.com/KeysLumber123", "Shopping: Island Shops And Boutiques", ""),
    ("", "Greeen House", "", "", "(305) 522-2382", "https://www.thegreeenhouse.com", "https://www.facebook.com/p/The-Greeen-House-Dispensary-of-Islamorada-82751-Overseas-Hwy-Unit-2-100093460624122/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Habitat for Humanity of the Upper Keys ReStore", "", "", "(305) 767-3190", "https://www.habitatupperkeys.org", "https://www.facebook.com/habitatupperkeys/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Holy Smokes Islamorada", "", "", "(305) 998-3738", "https://www.holysmokeskeys.com", "https://www.facebook.com/p/Holy-Smokes-Islamorada-Fl-100083328851258/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Islamorada Hemp Company", "", "islamoradahempcompany@gmail.com", "(305) 453-6432", "https://www.islamoradahempcompany.com", "https://www.facebook.com/islamoradahempco/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Islamorada Mercantile", "", "", "(305) 735-4942", "https://www.islamoradamercantile.com", "https://www.facebook.com/IslamoradaMercantile/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Islamorada Outdoor Furniture", "", "kenandalice@live.com", "(609) 287-1767", "https://teaknearme.com", "https://www.facebook.com/people/Islamorada-Outdoor-Furniture/100063774116653/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Island Home Garden Center", "", "", "(786) 971-2299", "https://www.islandhomegardencenter.com", "https://www.facebook.com/IslandHomeGarden/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Island Trendz at Amara Cay", "", "", "(305) 664-0095", "https://islandtrendzboutique.business.site", "https://www.facebook.com/islandtrendztropical/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Keys Deep Apparel", "", "Sales@KeysDeep.com", "(786) 502-6640", "https://keysdeep.com", "https://www.facebook.com/keysdeep2021/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Keys Kritters", "", "keyskritters@bellsouth.net", "(305) 451-2627", "https://facebook.com/KeysKritters", "https://www.facebook.com/KeysKritters/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Keys Mercantile", "", "kmsales@keyslumber.com", "(305) 735-4141", "https://www.keyslumber.com", "", "Shopping: Island Shops And Boutiques", ""),
    ("", "Los Cayos Apparel", "", "contact@loscayosapparel.com", "(305) 522-3688", "https://www.loscayosapparel.com", "https://www.facebook.com/loscayosapparel/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Miss Monroe Boutique", "", "", "(305) 440-3951", "https://www.shopmissmonroe.com", "https://www.facebook.com/missmonroeboutique/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Mystical Mermaid", "", "themysticalmermaid@hotmail.com", "(305) 395-2019", "https://themysticalmermaid.business.site", "https://www.facebook.com/themysticalmermaid/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Natacha's Boutique & Braids", "", "natachaboutique@hotmail.com", "(305) 393-1798", "https://www.natachasboutiquefloridakeys.com", "https://www.facebook.com/p/Natachas-Boutique-100049697411881/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Ocean Gardens", "", "info@oceangardensandgifts.com", "(305) 664-2793", "https://www.oceangardensandgifts.com", "https://www.facebook.com/oceangardensandgifts/", "Shopping: Island Shops And Boutiques", ""),
    ("ILI", "Olive Morada", "", "", "(305) 735-4375", "https://www.olivemorada.com", "https://www.facebook.com/oliveoilmorada", "Shopping: Island Shops And Boutiques", ""),
    ("", "Publix Super Market", "", "", "(305) 664-4890", "https://www.publix.com", "https://www.facebook.com/Publix1813/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Royal Furniture & Design", "", "", "(305) 451-5700", "https://www.keysfurniture.com", "https://www.facebook.com/KeysRoyalFurniture/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Salt + Sea", "", "", "(305) 664-0021", "https://www.threewatersresort.com", "https://www.facebook.com/threewatersresort/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Sandal Factory Outlet/T-Shirt City", "", "Joshl@sandalfactory.com", "(305) 664-9700", "https://www.sandalfactory.com", "", "Shopping: Island Shops And Boutiques", ""),
    ("", "Sea Dragon Exotic Island Décor", "", "", "(305) 664-0048", "https://www.seadragonfurniture.com", "https://www.facebook.com/Seadragonfurniture/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Sea La Vie Beach Boutique", "", "", "(305) 741-7576", "", "https://www.facebook.com/p/Sea-La-Vie-Beach-Boutique-100093622184536/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Shell World", "", "", "(305) 852-8245", "https://www.shellworldflkeys.com", "https://www.facebook.com/shellworldflkeys/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Southern Tide", "", "", "(305) 239-0803", "https://www.southerntide.com", "https://www.facebook.com/southerntideislamorada/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Tom Thumb Food Store", "", "", "(305) 852-7242", "https://www.mytomthumb.com", "https://www.facebook.com/MyTomThumb/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Trading Post", "", "", "(305) 664-2571", "https://www.tradingpostfloridakeys.com", "https://www.facebook.com/TheTradingPostIslamorada/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Tropical Optical", "", "TropicalOpticalKeys@gmail.com", "(305) 664-2665", "https://www.tropicaloptical.com", "", "Shopping: Island Shops And Boutiques", ""),
    ("", "Wild Lily Boutique", "", "liz@wildlilyboutique.com", "(305) 741-7276", "https://www.wildlilyboutique.com", "https://www.facebook.com/WildLilyBoutique/", "Shopping: Island Shops And Boutiques", ""),
    ("", "Zero Dress Code", "", "", "(305) 664-0800", "https://www.zerodresscode.com", "https://www.facebook.com/ZeroDressCode/", "Shopping: Island Shops And Boutiques", ""),
    # LUXURY LODGING
    ("", "Caribbean Resort", "", "", "(305) 664-2235", "https://www.thecaribbeanresort.com", "https://www.facebook.com/TheCaribbeanResort/", "Places to Stay: Luxury Lodging", ""),
    ("", "Casa Morada", "", "info@casamorada.com", "(305) 664-0044", "https://www.casamorada.com", "https://www.facebook.com/casa.morada/", "Places to Stay: Luxury Lodging", ""),
    ("", "Hawks Cay Resort", "", "", "(305) 289-2979", "https://www.hawkscay.com", "https://www.facebook.com/hawkscayresort/", "Places to Stay: Luxury Lodging", ""),
    ("", "Islander Resort", "", "info@islanderfloridakeys.com", "(305) 664-2031", "https://www.islanderfloridakeys.com", "https://www.facebook.com/IslanderResort/", "Places to Stay: Luxury Lodging", ""),
    ("", "Islands of Islamorada", "", "info@theislandsofislamorada.com", "(305) 440-3255", "https://www.theislandsofislamorada.com", "https://www.facebook.com/theislandsofislamorada/", "Places to Stay: Luxury Lodging", ""),
    ("", "Kona Kai Resort, Gallery and Botanic Garden", "", "info@konakairesort.com", "(305) 852-7200", "https://www.konakairesort.com", "https://www.facebook.com/KonaKaiResortGalleryandBotanicGarden/", "Places to Stay: Luxury Lodging", ""),
    ("", "Moorings Village", "", "info@mooringsvillage.com", "(305) 664-4708", "https://www.themooringsvillage.com", "https://www.facebook.com/mooringsvillage/", "Places to Stay: Luxury Lodging", ""),
    # MODERATE LODGING
    ("", "Amara Cay Resort", "", "reservations@amaracayresort.com", "(844) 831-1188", "https://www.islamoradaresortcollection.com", "https://www.facebook.com/AmaraCayResort/", "Places to Stay: Moderate Lodging", ""),
    ("", "Amoray Dive Center & Resort", "", "amoraydive@amoray.com", "(305) 451-3595", "https://www.amoray.com", "https://www.facebook.com/amoraydiveresort/", "Places to Stay: Moderate Lodging", ""),
    ("", "Atlantic Bay Resort", "", "", "(305) 852-5248", "https://www.atlanticbayresort.com", "https://www.facebook.com/p/Atlantic-Bay-Resort-100057658329518/", "Places to Stay: Moderate Lodging", ""),
    ("", "Breezy Palms Resort", "", "sales@breezypalms.com", "(305) 664-2361", "https://www.breezypalms.com", "https://www.facebook.com/p/Breezy-Palms-Resort-61571237185592/", "Places to Stay: Moderate Lodging", ""),
    ("", "Chesapeake Beach Resort", "", "sales@chesapeake-resort.com", "(305) 664-4662", "https://www.chesapeake-resort.com", "https://www.facebook.com/ChesapeakeBeachResort/", "Places to Stay: Moderate Lodging", ""),
    ("", "Coconut Palm Inn", "", "", "(305) 852-3017", "https://www.coconutpalminn.com", "https://www.facebook.com/CoconutPalmInn/", "Places to Stay: Moderate Lodging", ""),
    ("", "Coral Bay Resort", "", "info@coralbayresort.com", "(305) 664-5568", "https://www.coralbayresort.com", "https://www.facebook.com/p/Coral-Bay-Resort-100057269087899/", "Places to Stay: Moderate Lodging", ""),
    ("", "Drop Anchor Resort & Marina", "", "office@dropanchorislamorada.com", "(305) 664-4863", "https://www.dropanchorislamorada.com", "https://www.facebook.com/DropAnchorResort/", "Places to Stay: Moderate Lodging", ""),
    ("", "Glunz Ocean Beach Hotel & Resort", "", "info@glunzoceanbeachhotel.com", "(305) 289-0525", "https://www.glunzoceanbeachhotel.com", "https://www.facebook.com/glunzbeachhotel/", "Places to Stay: Moderate Lodging", ""),
    ("", "Gulf View Waterfront Resort", "", "", "(305) 289-1414", "https://www.gulfviewwaterfrontresort.com", "https://www.facebook.com/GulfViewWaterfrontResort305/", "Places to Stay: Moderate Lodging", ""),
    ("", "Island Bay Resort", "", "host@islandbayresort.com", "(305) 852-4087", "https://www.islandbayresort.com", "https://www.facebook.com/theislandbay/", "Places to Stay: Moderate Lodging", ""),
    ("", "Islander Bayside", "", "info@islanderbaysidevillas.com", "(305) 664-0082", "https://www.islanderbaysidevillas.com", "https://www.facebook.com/IslanderBaysideTownhomes/", "Places to Stay: Moderate Lodging", ""),
    ("", "Kon Tiki Resort", "", "", "(305) 664-4702", "https://www.kontiki-resort.com", "https://www.facebook.com/Kontikiresortisla/", "Places to Stay: Moderate Lodging", ""),
    ("", "La Jolla Resort", "", "reservations@lajollaresort.com", "(305) 664-9213", "https://www.lajollaresort.com", "https://www.facebook.com/lajollaresort/", "Places to Stay: Moderate Lodging", ""),
    ("", "La Siesta Resort & Villas", "", "", "(855) 228-0641", "https://www.islamoradaresortcollection.com", "https://www.facebook.com/LaSiestaResortandMarina/", "Places to Stay: Moderate Lodging", ""),
    ("", "Lime Tree Bay Resort", "", "info@limetreebayresort.com", "(305) 664-4740", "https://www.limetreebayresort.com", "https://www.facebook.com/limetreebay/", "Places to Stay: Moderate Lodging", ""),
    ("", "Little Basin Villas", "", "reservations@newmanhospitality.com", "(305) 363-8999", "https://www.littlebasinvillas.com", "https://www.facebook.com/littlebasinvillas/", "Places to Stay: Moderate Lodging", ""),
    ("", "Oceanview Inn & Pub", "", "", "(305) 664-8052", "https://www.theocean-view.com", "https://www.facebook.com/ovsportspub/", "Places to Stay: Moderate Lodging", ""),
    ("", "Pines and Palms Resort", "", "", "(305) 664-4343", "https://www.pinesandpalms.com", "https://www.facebook.com/pinesandpalmsresort/", "Places to Stay: Moderate Lodging", ""),
]

with open("members_updated.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(FIELDNAMES)
    for row in ROWS:
        writer.writerow(row)

total = len(ROWS)
with_email = sum(1 for r in ROWS if r[3])
with_fb = sum(1 for r in ROWS if r[6])
print(f"Written {total} rows")
print(f"Rows with email: {with_email}")
print(f"Rows with Facebook: {with_fb}")
